data_transformation:
  data_path: artifacts/data_ingestion/winequality-red.csv
  root_dir: artifacts/data_transformation
  test_data_path: artifacts/data_transformation/test.csv
  train_data_path: artifacts/data_transformation/train.csv
