artifacts_root: artifacts
data_ingestion:
  local_data_file: artifacts/data_ingestion/data.zip
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/WisdomAnalyst/FIFA-21-DATA-CLEANING-/raw/refs/heads/main/winequality-data.zip
  unzip_dir: artifacts/data_ingestion
data_transformation:
  data_path: artifacts/data_ingestion/winequality-red.csv
  root_dir: artifacts/data_transformation
  test_data_path: artifacts/data_transformation/test.csv
  train_data_path: artifacts/data_transformation/train.csv
data_validation:
  STATUS_FILE: artifacts/data_validation/status.txt
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
model_evaluation:
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/WisdomAnalyst/End-to-end-Machine-Learning-Project-with-Mlflow.mlflow
  model_path: artifacts/model_trainer/model.joblib
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
model_trainer:
  model_name: model.joblib
  root_dir: artifacts/model_trainer
  test_data_path: artifacts/data_transformation/test.csv
  train_data_path: artifacts/data_transformation/train.csv
